spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_order_service?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none


server:
  servlet:
    context-path: /order_service
  port: 8080


# SQL statements and trace
#logging:
#  pattern:
#    console: '%d: %msg%n'
#  file: /var/log/springboot/order_service.log
#  level:
#    com.phenix.LoggerTest: debug