spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_order_service?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: false
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 200       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0    # 连接池中的最小空闲连接

  # 返回数据中消除json数据中null项
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /order_service
  port: 8080


# SQL statements and trace
#logging:
#  pattern:
#    console: '%d: %msg%n'
#  file: /var/log/springboot/order_service.log
#  level:
#    com.phenix.LoggerTest: debug/